### PR TITLE
Return Writer on finalize

### PR DESCRIPTION
**Pull request by wyozi**
Otherwise there's no way to access the Writer anymore.

TBH I think my API suggestion kinda sucks but I accept suggestions.

### CODE REVIEW

**Comment by kornelski** [comment]
How about `Result<W, W>`? It's a weird type, but technically good way to report a failure and return something at the same time.

`(bool, W)` might work too.

**Comment by kornelski** [comment]
and making it `try_finalize()` would be backwards compatible (finalize can call it and throw away the result)

**Comment by wyozi** [comment]
I like that. I implemented `Result` in the newest commit.

**Comment by kornelski** [comment]
Thanks

**Pull request merged**
